name: adaptive_icons
description: A series of icons that adapt to the current platform's look.

version: 1.2.0

homepage: https://github.com/zippa-pizza/adaptive_icons
repository: https://github.com/zippa-pizza/adaptive_icons

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
